server:
  context-path: '/micro'
  port: 8080
    
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://caplonsgprd-1.integration.ibmcloud.com:15439/inventorydb
    username: dbuser
    password: Pass4dbUse3R
  jpa:
    database: MYSQL